### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by corneliusellen** [anthony-iacono/mod_0_assessment#1]
@anthony-iacono Solid work on this. I can tell you have a solid understanding of JavaScript datatypes and how to model data using objects. You are officially technical ready. Keep up the hard work moving forward and let me know if you have any questions. As mentioned on the Mod 0 site, we will be reviewing your Mod 1 Prework to determine promotion to Mod 1 - finish strong!

I have one important piece of feedback:
- for your ModelA, there is a syntax error. Best practice is to _always_ check that your code is syntactically valid before submitting it. You can do this easily by pasting the code in the browser console. Can you identify the syntax error you made and fix it?

**Comment by anthony-iacono** [comment]
I fixed the syntax error in modelA.js; next time I'll be sure to use a `console.log` to check for this. Thanks, Ellen!
